import { useEffect, useState } from 'react'
import { getBaseUrl } from './api'
import './claude.css'
const base = () => getBaseUrl()
const api = (path, options) => fetch(`${base()}/api${path}`, options)
const text = event => event?.type === 'result' ? event.result : event?.type === 'assistant' ? (event.message?.content || []).map(x=>x.text || `[${x.type}]`).join('') : event?.type ? `[${event.type}] ${event.subtype || ''}` : ''
export default function ClaudePanel() {
  const [workspaces,setWorkspaces]=useState([]),[workspaceId,setWorkspaceId]=useState(''),[task,setTask]=useState(''),[mode,setMode]=useState('plan'),[running,setRunning]=useState(false),[logs,setLogs]=useState([])
  useEffect(()=>{api('/claude/workspaces').then(r=>r.json()).then(items=>{setWorkspaces(items);setWorkspaceId(items[0]?.id||'')})},[])
  async function run(){const workspace=workspaces.find(x=>x.id===workspaceId);if(!task.trim()||!workspace||running)return;if(!confirm(`${mode==='acceptEdits'?'Claude 可以修改文件。':'Claude 将仅规划，不自动修改文件。'}\n\n工作目录：${workspace.path}\n\n确定执行吗？`))return;setRunning(true);setLogs([]);try{const response=await api('/claude/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:task,workspace_id:workspaceId,mode,confirmed:true})});if(!response.ok)throw new Error((await response.json()).detail);const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';while(true){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const events=pending.split('\n\n');pending=events.pop();for(const item of events){const raw=item.replace(/^data: /,'');if(raw==='[DONE]')continue;const data=JSON.parse(raw);setLogs(items=>[...items,data.error?`错误：${data.error}`:text(data.event)||data.text||''])}}}catch(error){setLogs(items=>[...items,`错误：${error.message}`])}finally{setRunning(false)}}
  return <section className="claude"><header><h1>Claude Code 执行</h1><p>在白名单工作目录中调用本机 Claude Code。每次执行都会要求确认。</p></header><div className="claude-body"><label>工作目录<select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name} · {w.path}</option>)}</select></label><label>执行权限<select value={mode} onChange={e=>setMode(e.target.value)}><option value="plan">仅规划（不自动编辑）</option><option value="acceptEdits">允许编辑文件</option></select></label><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="例如：检查这个项目的结构并列出改进建议；或实现一个具体功能。"/><button className="primary" onClick={run} disabled={running||!workspaces.length}>{running?'Claude 正在执行…':'执行任务'}</button><p className="safety">Claude 会使用本机已登录的权限。仅在你信任的设备与网络中部署工作台。</p><pre className="run-log">{logs.length?logs.join('\n\n'):'执行过程会显示在这里。'}</pre></div></section>
}
